-- MySQL Script generated by MySQL Workbench
-- Thu May  4 16:30:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestionInventaireInformatique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestionInventaireInformatique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestionInventaireInformatique` DEFAULT CHARACTER SET utf8 ;
USE `GestionInventaireInformatique` ;

-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`storagePlaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`storagePlaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `room name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date of purchase` DATE NOT NULL,
  `renewal date` DATE NOT NULL,
  `quantity` SMALLINT(4) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `archived` TINYINT(1) NOT NULL,
  `module_id` INT NOT NULL,
  `storage place_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_material_module_idx` (`module_id` ASC) VISIBLE,
  INDEX `fk_material_storage place_idx` (`storage place_id` ASC) VISIBLE,
  INDEX `fk_material_brand_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_material_type_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_materials_modules`
    FOREIGN KEY (`module_id`)
    REFERENCES `GestionInventaireInformatique`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_storage places1`
    FOREIGN KEY (`storage place_id`)
    REFERENCES `GestionInventaireInformatique`.`storagePlaces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `GestionInventaireInformatique`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `GestionInventaireInformatique`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionInventaireInformatique`.`modifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionInventaireInformatique`.`modifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modification` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `material_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_modification_material_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_modifications_materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `GestionInventaireInformatique`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
